# Site settings
title: Colin Woodford Design
email: colin@cwoodford.com
description: >
  Colin Woodfor: The Art of Style.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://colinwoodforddesign.com/" # the base hostname & protocol for your site
twitter_username: woodfordcolinnoel
github_username:  woodfordcolinnoel
address: |
  261 Fawn Drive
  San Anselmo
  California 94960-1159

# Build settings
markdown: kramdown
